Support multiple redis servers
jianshucom/norton pull request #20
Opened 2017-09-25 09:59 UTC by xuncheng

### Usage 
``` ruby
class Post
  include Norton::Timestamp

  timestamp :published_at, :redis => :tmp

  def id
    @id ||= 99
  end
end
```

2017-10-08 13:14 UTC, larryzhao requested changes

2017-10-08 13:14 UTC, larryzhao commented on lib/norton/helper.rb
> +      def norton_value_redis(name)
`norton_value_redis_pool` 把，更清晰一点，我一开始看了好久

2017-10-08 13:14 UTC, larryzhao commented on lib/norton/hash_map.rb
> +              Norton::Objects::Hash.new(norton_value_key(name), :redis => redis)
这个我觉得就直接传 attr 的 option hash 进去，也便于扩展，不要直接传 pool 的 instance，pool 的 instance 还是用的时候从hash 里面拿

2017-10-09 03:09 UTC, xuncheng commented on lib/norton/hash_map.rb
> +              Norton::Objects::Hash.new(norton_value_key(name), :redis => redis)
这个 pool 是和 field 关联的，在初始化 `Norton::Objects::Hash` 的时候，传的时候 key 而不是 field，所以在 `Norton::Objects::Hash` 里没办法拿到 pool

2017-10-10 14:12 UTC, larryzhao approved these changes

2017-10-11 02:32 UTC, merged